# [SPRING]

spring.application.name=autoalquiler
spring.datasource.url=jdbc:sqlite:./autoalquiler.db?foreign_keys=true
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
#spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# Evitar que Hibernate intente crear las tablas si el script ya lo hace
spring.jpa.hibernate.ddl-auto=none
spring.sql.init.mode=always
spring.sql.init.separator=//
spring.messages.basename=messages
spring.messages.encoding=UTF-8
spring.messages.fallback-to-system-locale=true
spring.mvc.view.prefix=/templates/
spring.output.ansi.enabled=ALWAYS

# [LOGS]
logging.file.name=logs/autoalquiler.log 
logging.level.org.springframework.security=DEBUG 
logging.level.com.json.AutoAlquiler=DEBUG
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
logging.level.org.hibernate.orm.jdbc.bind=TRACE

# [SERVER]
server.error.include-stacktrace=never
server.error.include-message=always
server.error.whitelabel.enabled=false
server.tomcat.connection-upload-timeout=20000
server.reactive.session.cookie.max-age=20000
server.port=8070

